name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Build project with Maven (produces shaded JAR)
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # 4. Upload shaded JAR artifact (optional)
      - name: Upload shaded JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-maven-shaded-jar
          path: target/hello-maven-shaded.jar

      # 5. Update dependency graph for Dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      # 6. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build Docker image using the shaded JAR
      - name: Build Docker image
        run: |
          JAR_PATH=target/hello-maven-shaded.jar
          echo "Using JAR: $JAR_PATH"
          docker build --build-arg JAR_FILE=$JAR_PATH -t ${{ secrets.DOCKER_USERNAME }}/hello-maven:latest .

      # 8. Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-maven:latest
